# forgepeek config generator — sourced by the dispatcher for 'forgepeek
# config'. Single source of truth for the app.ini snippets quoted in the
# docs and printed by install.sh. Reads each handler's machine-readable
# header (extensions, mode) and emits one [markup.*] stanza per extension —
# one per extension because Forgejo passes only file content on stdin, so
# the extension must be baked into RENDER_COMMAND.
#
# Sanitized handlers additionally get [markup.sanitizer.<name>.*] rules:
# the elements/attributes the shared HTML helpers emit, value-constrained
# by REGEXP, plus ALLOW_DATA_URI_IMAGES (without which previews are
# silently blank). iframe handlers get RENDER_CONTENT_MODE = iframe and no
# sanitizer rules (the sanitizer does not apply to iframe content).
#
# NOTE (ini syntax): regexp values below deliberately avoid the sequences
# " #" and " ;" — go-ini would treat them as inline comment starts.

FP_STYLE_RE='^[#%a-zA-Z0-9:;,. -]+$'
FP_CLASS_RE='^forgepeek[a-z -]*$'

fp_emit_stanza() { # NAME EXT CMDPATH MODE
    printf '[markup.%s]\n' "$1"
    printf 'ENABLED = true\n'
    printf 'FILE_EXTENSIONS = %s\n' "$2"
    printf 'RENDER_COMMAND = "%s render %s"\n' "$3" "${2#.}"
    printf 'IS_INPUT_FILE = false\n'
    printf 'RENDER_CONTENT_MODE = %s\n' "$4"
    printf 'NEED_POSTPROCESS = false\n'
}

fp_emit_sanitizer() { # NAME
    printf '\n[markup.sanitizer.%s.data-uri]\n' "$1"
    printf 'ALLOW_DATA_URI_IMAGES = true\n'
    printf '\n[markup.sanitizer.%s.div-class]\n' "$1"
    printf 'ELEMENT = div\nALLOW_ATTR = class\nREGEXP = %s\n' "$FP_CLASS_RE"
    for _fp_el in div p img pre details; do
        printf '\n[markup.sanitizer.%s.%s-style]\n' "$1" "$_fp_el"
        printf 'ELEMENT = %s\nALLOW_ATTR = style\nREGEXP = %s\n' \
            "$_fp_el" "$FP_STYLE_RE"
    done
}

fp_emit_config() {
    _fp_cmdpath="$FORGEPEEK_ROOT/forgepeek"
    _fp_filter=''
    while [ $# -gt 0 ]; do
        case $1 in
            --path)
                [ $# -ge 2 ] || { echo "forgepeek config: --path needs a value" >&2; exit 2; }
                _fp_cmdpath="$2/forgepeek"
                shift 2
                ;;
            -*)
                echo "forgepeek config: unknown option $1" >&2
                exit 2
                ;;
            *)
                _fp_filter="$_fp_filter $1"
                shift
                ;;
        esac
    done

    printf ';; ---------------------------------------------------------------\n'
    printf ';; forgepeek external renderers — generated by "forgepeek config"\n'
    printf ';; Append to app.ini and restart Forgejo. Re-run after adding or\n'
    printf ';; removing handlers. Docs: docs/INSTALL.md\n'
    printf ';; ---------------------------------------------------------------\n'

    for _fp_h in $(fp_handlers); do
        _fp_hname=$(basename "$_fp_h")
        if [ -n "$_fp_filter" ]; then
            case " $_fp_filter " in
                *" $_fp_hname "*) ;;
                *) continue ;;
            esac
        fi
        _fp_mode=$(fp_header "$_fp_h" mode)
        [ "$_fp_mode" = iframe ] || _fp_mode=sanitized
        _fp_exts=$(fp_header "$_fp_h" extensions | tr ',' ' ')
        for _fp_e in $_fp_exts; do
            _fp_name="forgepeek-${_fp_e#.}"
            printf '\n'
            fp_emit_stanza "$_fp_name" "$_fp_e" "$_fp_cmdpath" "$_fp_mode"
            if [ "$_fp_mode" = sanitized ]; then
                fp_emit_sanitizer "$_fp_name"
            fi
        done
    done
}
